#!/usr/bin/env bash
#
# Control Tilt as a background process.
#

if ! type -p tilt > /dev/null; then
    echo "Tilt not found in $PATH" >&2
    exit 1
fi

export TILT_PORT=${TILT_PORT-10350}
export TILT_WEB_MODE=${TILT_WEB_MODE-prod}

tilt_pid=$(tilt get session -o jsonpath='{.items[0].status.pid}' 2> /dev/null)

tilt_start() {
    if [ "$tilt_pid" ]; then
        return 0
    fi

    local tiltfile=${1-./Tiltfile}
    if [ ! -f $tiltfile ]; then
        echo "No Tiltfile specified" >&2
        exit 1
    fi

    cd $(dirname $tiltfile)
    set -m
    tilt up --legacy=false -f $tiltfile >/dev/null 2>&1 &
    return 0
}

current_tiltfile() {
    tilt get session -o jsonpath='{.items[0].spec.tiltfilePath}' 2> /dev/null
}

tilt_stop() {
    if [ "$tilt_pid" ]; then
        kill $tilt_pid
    fi
    return 0
}

cmd=$1
shift
tiltfile=$1

case $cmd in
    start)
        tilt_start "$tiltfile"
        ;;

    stop)
        tilt_stop
        ;;

    restart)
        tiltfile=$(current_tiltfile)
        tilt_stop
        tilt_pid=
        tilt_start "$tiltfile"
        ;;

    open)
        tilt_start "$tiltfile"
        open http://localhost:$TILT_PORT
        ;;

    reopen)
        tilt_stop
        tilt_pid=
        tilt_start "$tiltfile"
        open http://localhost:$TILT_PORT
        ;;

    down)
        tiltfile=$(current_tiltfile)
        tilt_stop
        tilt down -f $tiltfile
        ;;

    pid)
        echo $tilt_pid
        ;;

    *)
        echo "usage: tilt-daemon <start|stop> [Tiltfile]"
        ;;
esac
